module.exports={
  HTTP_URL:"http://192.168.1.104:8080",
  IsRegister_URL:"/isRegister",
  SetUserinfo_URL:"/setUserinfo",
  GetUserinfo_URL:"/getUserinfo",
  UpdateUserinfo_URL:"/setUserinfo",
  SetTakeAddress_URL:"/setTakeAddress",
  GetTakeAddress_URL:"/getTakeAddress",
  UpdateTakeAddress_URL:"/updateTakeAddress",
  DeleteTakeAddress_URL:"/deleteTakeAddress",
  AuthorizeLogin_URL:"/authorizeLogin",
  setDgInfo_URL:"/setDgInfo",
  setDnInfo_URL:"/setDnInfo",
  setDbInfo_URL:"/setDbInfo",
  GrapOrder_URL:"/grapOrder",
  secret:"d51a1533fa18e8b33534ef73a326fa4e",
  appid:'wx68fd34d6b27b8e78',
  key:"WXCBZ-UPICJ-5V3FI-KA5U4-UMB2J-57B6A"
}