module.exports={
  HTTP_URL:"http://192.168.1.101:8080",
  IsRegister_URL:"/isRegister",
  SetUserinfo_URL:"/setUserinfo",
  GetUserinfo_URL:"/getUserinfo",
  UpdateUserinfo_URL:"/setUserinfo",
  SetTakeAddress_URL:"/setTakeAddress",
  GetTakeAddress_URL:"/getTakeAddress",
  UpdateTakeAddress_URL:"/updateTakeAddress",
  DeleteTakeAddress_URL:"/deleteTakeAddress",
  AuthorizeLogin_URL:"/authorizeLogin",
  setDgInfo_URL:"/setDgInfo",
  setDnInfo_URL:"/setDnInfo",
  setDbInfo_URL:"/setDbInfo",
  secret:"1dd31e8904ba78dc4933ce735435825f",
  appid:'wxe5aec76fc17b9daa',
  key:"3YOBZ-5BQKX-TNF4K-ZQZ76-WBVLT-HQFRZ"
}